### ISSUE TITLE
스킨이 정상적으로 작동하지 않습니다.

### ISSUE THREAD

**Issue by pseol2190** [2DU/openNAMU-Skin-Before_Namu#4]
스크린샷:
![screenshot](https://user-images.githubusercontent.com/39310079/42378996-48c37f22-8164-11e8-9ee6-869b0ccfed66.png)

**Comment by 2DU** [comment]
스킨 이름 개편 했는데 깜박하고 다 고치지 않았나봐요

내일 고치죠

**Comment by 2DU** [comment]
스킨 이름을 바꿔주세요
